all:
  children:
    env_staging:
      children:
        zone_management:
          children:
            control_plane:
              hosts:
                stg-mgmt-ansible-01:
                stg-mgmt-bastion-01:
        zone_core_services:
          children:
            directory_services:
              hosts:
                stg-core-dc-01:
                stg-core-dc-02:
            time_services:
              hosts:
                stg-core-dc-01:
        zone_monitoring_security:
          children:
            log_pipeline:
              hosts:
                stg-mon-log-01:
            wazuh_manager:
              hosts:
                stg-sec-wazuh-01:
        phase_environment:
          children:
            control_plane:
            directory_services:
            time_services:
            log_pipeline:
            wazuh_manager:

    monitored_endpoints:
      hosts:
        stg-mon-log-01:
    windows_security_endpoints:
      hosts:
        stg-core-dc-01:

    os_linux:
      hosts:
        stg-mgmt-ansible-01:
        stg-mgmt-bastion-01:
        stg-mon-log-01:
        stg-sec-wazuh-01:

    os_windows:
      hosts:
        stg-core-dc-01:
        stg-core-dc-02:
