all:
  children:
    env_test_core:
      children:
        zone_management:
          children:
            control_plane:
              hosts:
                tc-mgmt-ansible-01:
                tc-mgmt-bastion-01:
        zone_core_services:
          children:
            directory_services:
              hosts:
                tc-core-dc-01:
                tc-core-dc-02:
            time_services:
              hosts:
                tc-core-dc-01:
        zone_monitoring_security:
          children:
            log_pipeline:
              hosts:
                tc-mon-log-01:
            wazuh_manager:
              hosts:
                tc-sec-wazuh-01:
        phase_1_test_core:
          children:
            control_plane:
            directory_services:
            time_services:
            log_pipeline:
            wazuh_manager:

    os_linux:
      hosts:
        tc-mgmt-ansible-01:
        tc-mgmt-bastion-01:
        tc-mon-log-01:
        tc-sec-wazuh-01:

    os_windows:
      hosts:
        tc-core-dc-01:
        tc-core-dc-02:
