all:
  children:
    env_production:
      children:
        zone_management:
          children:
            control_plane:
              hosts:
                prd-mgmt-ansible-01:
                prd-mgmt-bastion-01:
        zone_core_services:
          children:
            directory_services:
              hosts:
                prd-core-dc-01:
                prd-core-dc-02:
            time_services:
              hosts:
                prd-core-dc-01:
        zone_monitoring_security:
          children:
            log_pipeline:
              hosts:
                prd-mon-log-01:
            wazuh_manager:
              hosts:
                prd-sec-wazuh-01:
        phase_environment:
          children:
            control_plane:
            directory_services:
            time_services:
            log_pipeline:
            wazuh_manager:

    monitored_endpoints:
      hosts:
        prd-mon-log-01:
    windows_security_endpoints:
      hosts:
        prd-core-dc-01:

    os_linux:
      hosts:
        prd-mgmt-ansible-01:
        prd-mgmt-bastion-01:
        prd-mon-log-01:
        prd-sec-wazuh-01:

    os_windows:
      hosts:
        prd-core-dc-01:
        prd-core-dc-02:
